In [5]:
import numpy as np
import pandas as pd
import math

In [ ]:
# NUMPY PROBLEMS

In [ ]:
 # 1. Creating Arrays 
 # ● Question: Using NumPy, create a 1D array of 20 random integers between 10 and 50. Then, find the mean and standard deviation of the array. 
 # ● Hint: Use np.random.randint() for creating 1D array

In [ ]:
array = np.random.randint(10, 50, size=20)
mean = np.mean(array)
std_deviation = np.std(array)
print("Array:", array)
print("Mean:", mean)
print("Standard Deviation:", std_deviation)

Array: [39 24 34 33 47 21 14 15 35 18 20 40 34 16 18 24 39 30 41 45]
Mean: 29.35
Standard Deviation: 10.42245172692107


In [ ]:
# Output:

# Array: [39 24 34 33 47 21 14 15 35 18 20 40 34 16 18 24 39 30 41 45]
# Mean: 29.35
# Standard Deviation: 10.42245172692107

In [ ]:
# 2. Array Reshaping 
# ● Question: Create a 2D NumPy array of shape (6, 5) filled with random floats between 0 and 1. Reshape this array to have shape (5, 6) and print both 
# the original and reshaped arrays. 
# ● Hint: Use np.random.rand()

In [ ]:
original_array = np.random.rand(6, 5)
reshaped_array = original_array.reshape(5, 6)
print("Original Array (6, 5):",original_array)
print("\nReshaped Array (5, 6):",reshaped_array)

Original Array (6, 5): [[0.00197131 0.49116036 0.29795624 0.50950131 0.02302197]
 [0.75563026 0.07533919 0.26735207 0.19304928 0.89465959]
 [0.91043957 0.07945634 0.11984097 0.80147683 0.58052495]
 [0.24658498 0.93205945 0.01286012 0.68066955 0.56177367]
 [0.28619213 0.42662519 0.42208829 0.51731288 0.81259376]
 [0.26445516 0.16367714 0.16830335 0.67823556 0.22145353]]

Reshaped Array (5, 6): [[0.00197131 0.49116036 0.29795624 0.50950131 0.02302197 0.75563026]
 [0.07533919 0.26735207 0.19304928 0.89465959 0.91043957 0.07945634]
 [0.11984097 0.80147683 0.58052495 0.24658498 0.93205945 0.01286012]
 [0.68066955 0.56177367 0.28619213 0.42662519 0.42208829 0.51731288]
 [0.81259376 0.26445516 0.16367714 0.16830335 0.67823556 0.22145353]]


In [ ]:
# OUTPUT:
# Original Array (6, 5): [[0.00197131 0.49116036 0.29795624 0.50950131 0.02302197]
#  [0.75563026 0.07533919 0.26735207 0.19304928 0.89465959]
#  [0.91043957 0.07945634 0.11984097 0.80147683 0.58052495]
#  [0.24658498 0.93205945 0.01286012 0.68066955 0.56177367]
#  [0.28619213 0.42662519 0.42208829 0.51731288 0.81259376]
#  [0.26445516 0.16367714 0.16830335 0.67823556 0.22145353]]

# Reshaped Array (5, 6): [[0.00197131 0.49116036 0.29795624 0.50950131 0.02302197 0.75563026]
#  [0.07533919 0.26735207 0.19304928 0.89465959 0.91043957 0.07945634]
#  [0.11984097 0.80147683 0.58052495 0.24658498 0.93205945 0.01286012]
#  [0.68066955 0.56177367 0.28619213 0.42662519 0.42208829 0.51731288]
#  [0.81259376 0.26445516 0.16367714 0.16830335 0.67823556 0.22145353]]

In [ ]:
# 3. Array Indexing and Slicing 
# ● Question: Create a 2D array of shape (5, 5) filled with numbers from 1 to 25.  Extract a subarray that includes rows 2 to 4 and columns 1 to 3. 
# ● Hint: Use np.arange() and slicing techniques.

In [12]:
array = np.arange(1, 26).reshape(5, 5)
subarray = array[1:4, 0:3]
print("Original Array:",array)
print("\nExtracted Subarray (Rows 2 to 4 and Columns 1 to 3):",subarray)

Original Array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Extracted Subarray (Rows 2 to 4 and Columns 1 to 3): [[ 6  7  8]
 [11 12 13]
 [16 17 18]]


In [ ]:
# output:

# Original Array: [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]
#  [21 22 23 24 25]]

# Extracted Subarray (Rows 2 to 4 and Columns 1 to 3): [[ 6  7  8]
#  [11 12 13]
#  [16 17 18]]

In [ ]:
# 4. Array Operations 
# ● Question: Generate two 1D arrays A and B, each containing 10 random integers 
# between 1 and 100. Add the arrays together, then multiply the result by 2. Show 
# the results of each operation. 
# ● Hint: Use + for addition and * for multiplication.

In [13]:
A = np.random.randint(1, 101, size=10)
B = np.random.randint(1, 101, size=10)
sum_array = A + B
result_array = sum_array * 2
print("Array A:", A)
print("Array B:", B)
print("Sum of A and B:", sum_array)
print("Result after multiplying by 2:", result_array)


Array A: [ 9 46 86 92 41 90  3 28 56 67]
Array B: [ 28  23  19  15  65  84  53  29  36 100]
Sum of A and B: [ 37  69 105 107 106 174  56  57  92 167]
Result after multiplying by 2: [ 74 138 210 214 212 348 112 114 184 334]


In [ ]:
# output:

# Array A: [ 9 46 86 92 41 90  3 28 56 67]
# Array B: [ 28  23  19  15  65  84  53  29  36 100]
# Sum of A and B: [ 37  69 105 107 106 174  56  57  92 167]
# Result after multiplying by 2: [ 74 138 210 214 212 348 112 114 184 334]

In [ ]:
# 5. Broadcasting 
# ● Question: Create a 2D array A of shape (3, 4) filled with random integers between 
# 1 and 10. Create a 1D array B of shape (4,) with values [1, 2, 3, 4]. Add the 1D array 
# to the 2D array and explain how broadcasting works in this case. 
# 1 
# ● Hint: Use np.random.randint().

In [14]:
A = np.random.randint(1, 11, size=(3, 4))
B = np.array([1, 2, 3, 4])
result = A + B
print("Array A (3, 4):",A)
print("\nArray B (4,):",B)
print("\nResult of Broadcasting (A + B):",result)

Array A (3, 4): [[ 6  4  8  4]
 [ 4 10  4  5]
 [ 3  4  2  3]]

Array B (4,): [1 2 3 4]

Result of Broadcasting (A + B): [[ 7  6 11  8]
 [ 5 12  7  9]
 [ 4  6  5  7]]


In [ ]:
# Output

# Array A (3, 4): [[ 6  4  8  4]
#  [ 4 10  4  5]
#  [ 3  4  2  3]]

# Array B (4,): [1 2 3 4]

# Result of Broadcasting (A + B): [[ 7  6 11  8]
#  [ 5 12  7  9]
#  [ 4  6  5  7]]

In [ ]:
# 6. Finding Maximum/Minimum Values 
# ● Question: Create a 3x3 matrix of random integers between 1 and 100. Find the  row with the maximum sum, and then the maximum value in that row. 
# ● Hint: Use np.sum() and np.argmax()

In [15]:
matrix = np.random.randint(1, 101, size=(3, 3))
row_sums = np.sum(matrix, axis=1)
max_row_index = np.argmax(row_sums)
max_value_in_row = np.max(matrix[max_row_index])

print("Matrix:",matrix)
print("\nRow with Maximum Sum (Index):", max_row_index)
print("Maximum Value in that Row:", max_value_in_row)


Matrix: [[54 20  9]
 [66 42 25]
 [65 75 45]]

Row with Maximum Sum (Index): 2
Maximum Value in that Row: 75


In [ ]:
# output:

# Matrix: [[54 20  9]
#  [66 42 25]
#  [65 75 45]]

# Row with Maximum Sum (Index): 2
# Maximum Value in that Row: 75

In [ ]:
# 7. Linear Algebra 
# ● Question: Create two 2D arrays A and B, both of shape (2, 2), filled with random 
# integers. Compute the matrix multiplication of A and B using np.dot(). 
# ● Hint: Use np.random.randint() and np.dot().

In [17]:
A = np.random.randint(1, 11, size=(2, 2))
B = np.random.randint(1, 11, size=(2, 2))
result = np.dot(A, B)
print("Matrix A:",A)
print("\nMatrix B:",B)
print("\nMatrix Multiplication (A dot B):",result)

Matrix A: [[5 1]
 [4 6]]

Matrix B: [[8 7]
 [8 3]]

Matrix Multiplication (A dot B): [[48 38]
 [80 46]]


In [ ]:
# output:
# Matrix A: [[5 1]
#  [4 6]]

# Matrix B: [[8 7]
#  [8 3]]

# Matrix Multiplication (A dot B): [[48 38]
#  [80 46]]

In [18]:
# 8. Boolean Indexing 
# ● Question: Create an array of shape (6, 6) with random integers between 1 and 50. 
# Using boolean indexing, extract all values greater than 25. 
# ● Hint: Use boolean conditions like array > 25.

In [19]:
array = np.random.randint(1, 51, size=(6, 6))
values_greater_than_25 = array[array > 25]

print("Original Array:",array)
print("\nValues Greater Than 25:",values_greater_than_25)

Original Array: [[20 18  5 13 22 37]
 [27  8 47 29 13 39]
 [23 50 23  3 49 26]
 [18 14  9 42 26  6]
 [33  8 11 39 27 47]
 [17 49 43 37 22  8]]

Values Greater Than 25: [37 27 47 29 39 50 49 26 42 26 33 39 27 47 49 43 37]


In [20]:
# output:


# Original Array: [[20 18  5 13 22 37]
#  [27  8 47 29 13 39]
#  [23 50 23  3 49 26]
#  [18 14  9 42 26  6]
#  [33  8 11 39 27 47]
#  [17 49 43 37 22  8]]

# Values Greater Than 25: [37 27 47 29 39 50 49 26 42 26 33 39 27 47 49 43 37]

In [22]:
# 9. Statistics 
# ● Question: Create a 5x5 array of random floats between 0 and 1. Calculate the 
# median and variance along the columns and rows separately. 
# ● Hint: Use np.median() and np.var() with the axis parameter. 

In [23]:
array = np.random.rand(5, 5)
median_columns = np.median(array, axis=0)
median_rows = np.median(array, axis=1)
variance_columns = np.var(array, axis=0)
variance_rows = np.var(array, axis=1)

print("Array:",array)
print("\nMedian along columns:", median_columns)
print("Median along rows:", median_rows)
print("\nVariance along columns:", variance_columns)
print("Variance along rows:", variance_rows)


Array: [[0.85719375 0.24894146 0.05758433 0.22732627 0.50991127]
 [0.54436616 0.72990322 0.94045266 0.83078965 0.99838723]
 [0.5319726  0.6597536  0.28307224 0.55570352 0.32559736]
 [0.04093323 0.84040099 0.93970079 0.59635138 0.05707886]
 [0.2629381  0.62666384 0.16120272 0.18542908 0.70557806]]

Median along columns: [0.5319726  0.6597536  0.28307224 0.55570352 0.50991127]
Median along rows: [0.24894146 0.83078965 0.5319726  0.59635138 0.2629381 ]

Variance along columns: [0.07674545 0.03999162 0.1484248  0.05858684 0.10309627]
Variance along rows: [0.07780562 0.02598185 0.02059576 0.14505685 0.05318561]


In [24]:
# output:

# Array: [[0.85719375 0.24894146 0.05758433 0.22732627 0.50991127]
#  [0.54436616 0.72990322 0.94045266 0.83078965 0.99838723]
#  [0.5319726  0.6597536  0.28307224 0.55570352 0.32559736]
#  [0.04093323 0.84040099 0.93970079 0.59635138 0.05707886]
#  [0.2629381  0.62666384 0.16120272 0.18542908 0.70557806]]

# Median along columns: [0.5319726  0.6597536  0.28307224 0.55570352 0.50991127]
# Median along rows: [0.24894146 0.83078965 0.5319726  0.59635138 0.2629381 ]

# Variance along columns: [0.07674545 0.03999162 0.1484248  0.05858684 0.10309627]
# Variance along rows: [0.07780562 0.02598185 0.02059576 0.14505685 0.05318561]


In [25]:
# 10. Element-wise Operations 
# ● Question: Generate a 3x3 matrix of random integers between 1 and 10. Perform 
# the following element-wise operations: subtract 2 from each element, square each 
# element, and compute the reciprocal of each element. 
# ● Hint: Use standard arithmetic operations and np.reciprocal().

In [26]:
matrix = np.random.randint(1, 11, size=(3, 3))
subtracted_matrix = matrix - 2
squared_matrix = matrix ** 2
reciprocal_matrix = 1 / matrix


print("Original Matrix:",matrix)
print("\nMatrix After Subtracting 2:",subtracted_matrix)
print("\nMatrix After Squaring Each Element:",squared_matrix)
print("\nReciprocal of Each Element:",reciprocal_matrix)

Original Matrix: [[4 6 6]
 [3 8 8]
 [7 6 8]]

Matrix After Subtracting 2: [[2 4 4]
 [1 6 6]
 [5 4 6]]

Matrix After Squaring Each Element: [[16 36 36]
 [ 9 64 64]
 [49 36 64]]

Reciprocal of Each Element: [[0.25       0.16666667 0.16666667]
 [0.33333333 0.125      0.125     ]
 [0.14285714 0.16666667 0.125     ]]


In [27]:
# output:

# Original Matrix: [[4 6 6]
#  [3 8 8]
#  [7 6 8]]

# Matrix After Subtracting 2: [[2 4 4]
#  [1 6 6]
#  [5 4 6]]

# Matrix After Squaring Each Element: [[16 36 36]
#  [ 9 64 64]
#  [49 36 64]]

# Reciprocal of Each Element: [[0.25       0.16666667 0.16666667]
#  [0.33333333 0.125      0.125     ]
#  [0.14285714 0.16666667 0.125     ]]

In [28]:
# PANDAS PROBLEMS

In [29]:
data = pd.read_csv('auto-mpg.csv')

In [ ]:
# 1. Basic Exploration 
# Load the dataset into a Pandas DataFrame. Display: 
# ○ The first 10 rows 
# ○ The total number of rows and columns 
# ○ Summary statistics for numerical columns 

In [32]:
print(data.head(10)) 

    mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   
5  15.0          8         429.0        198    4341          10.0          70   
6  14.0          8         454.0        220    4354           9.0          70   
7  14.0          8         440.0        215    4312           8.5          70   
8  14.0          8         455.0        225    4425          10.0          70   
9  15.0          8         390.0        190    3850           8.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skyla

In [31]:
data.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

In [33]:
data.shape

(398, 9)

In [34]:
data.describe()

mpg   cylinders  displacement       weight  acceleration  \
count  398.000000  398.000000    398.000000   398.000000    398.000000   
mean    23.514573    5.454774    193.425879  2970.424623     15.568090   
std      7.815984    1.701004    104.269838   846.841774      2.757689   
min      9.000000    3.000000     68.000000  1613.000000      8.000000   
25%     17.500000    4.000000    104.250000  2223.750000     13.825000   
50%     23.000000    4.000000    148.500000  2803.500000     15.500000   
75%     29.000000    8.000000    262.000000  3608.000000     17.175000   
max     46.600000    8.000000    455.000000  5140.000000     24.800000   

       model year      origin  
count  398.000000  398.000000  
mean    76.010050    1.572864  
std      3.697627    0.802055  
min     70.000000    1.000000  
25%     73.000000    1.000000  
50%     76.000000    1.000000  
75%     79.000000    2.000000  
max     82.000000    3.000000

In [35]:
# 2. Filtering and Indexing 
# Find all cars manufactured in 1975 with a weight less than 3000. Return the  DataFrame with selected columns: car_name, weight, and mpg.

In [39]:
filtered_data = data[(data['model year'] == 1975) & (data['weight'] < 3000)]
filtered_data

Empty DataFrame
Columns: [mpg, cylinders, displacement, horsepower, weight, acceleration, model year, origin, car name]
Index: []

In [43]:
result = filtered_data[['cylinders', 'weight', 'mpg']]
result


Empty DataFrame
Columns: [cylinders, weight, mpg]
Index: []

In [45]:
# 3. Handling Missing Data 
# Identify if there are any missing values in the dataset. Replace missing values in the 
# horsepower column with the column's median.

In [46]:
print("Missing values in each column:")
print(data.isnull().sum())


Missing values in each column:
mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64


In [51]:
data['horsepower'] = pd.to_numeric(data['horsepower'], errors='coerce')
print("Missing values in 'horsepower':", data['horsepower'].isnull().sum())




Missing values in 'horsepower': 6


In [54]:
horsepower_median = data['horsepower'].median()
print(data['horsepower'].isnull().sum())

0


In [55]:
# 4. Data Transformation 
# Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [58]:
data['power_to_weight_ratio'] = data['horsepower'] / data['weight']
print(data[['mpg', 'horsepower', 'weight', 'power_to_weight_ratio']].head())


    mpg  horsepower  weight  power_to_weight_ratio
0  18.0       130.0    3504               0.037100
1  15.0       165.0    3693               0.044679
2  18.0       150.0    3436               0.043655
3  16.0       150.0    3433               0.043694
4  17.0       140.0    3449               0.040591


In [59]:
# 5. Group By 
# Group the cars by origin and calculate the mean mpg for each group


In [62]:
mean_mpg = data.groupby('origin')['mpg'].mean()
mean_mpg

origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

In [63]:
# 6. Sorting 
# Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg. 
# Apply Function 
# Create a new column performance_score using a custom function: 
# def performance_score(row): 
# return row['mpg'] * row['acceleration'] / row['weight'] 

In [66]:

top_10_cars = data.sort_values(by='mpg', ascending=False).head(10)
top_10_cars


mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0        93.5    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050954  
324               0.030806  
247               0.033816

In [69]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

data['performance_score'] = data.apply(performance_score, axis=1)
data


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  \
0            70       1  chevrolet chevelle malibu               0.037100   
1            70       1          buick skylark 320               0.044679   
2            70       1         plymouth satellite               0.043655   
3            70       1              amc rebel sst               0.043694   
4            70       1                ford torino               0.040591   
..          ...     ...                        ...                    ...   
393          82       1            ford mustang gl               0.030824   
394          82       2                  vw pickup               0.024413   
395          82       1              dodge rampage               0.036601   
396          82       1                ford ranger               0.030095   
397          82       1                 chevy s-10               0.030147   

     performance_score  
0             0.061644  
1             0.046710  
2             0.057625  
3             0.055928  
4             0.051754  
..                 ...  
393           0.150968  
394           0.508169  
395           0.161743  
396           0.198400  
397           0.221103  

[398 rows x 11 columns]

In [70]:
# 7. Apply this function to each row and store the result in the new column.

In [72]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

data['performance_score'] = data.apply(performance_score, axis=1)
data


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0    18.0          8         307.0       130.0    3504          12.0   
1    15.0          8         350.0       165.0    3693          11.5   
2    18.0          8         318.0       150.0    3436          11.0   
3    16.0          8         304.0       150.0    3433          12.0   
4    17.0          8         302.0       140.0    3449          10.5   
..    ...        ...           ...         ...     ...           ...   
393  27.0          4         140.0        86.0    2790          15.6   
394  44.0          4          97.0        52.0    2130          24.6   
395  32.0          4         135.0        84.0    2295          11.6   
396  28.0          4         120.0        79.0    2625          18.6   
397  31.0          4         119.0        82.0    2720          19.4   

     model year  origin                   car name  power_to_weight_ratio  \
0            70       1  chevrolet chevelle malibu               0.037100   
1            70       1          buick skylark 320               0.044679   
2            70       1         plymouth satellite               0.043655   
3            70       1              amc rebel sst               0.043694   
4            70       1                ford torino               0.040591   
..          ...     ...                        ...                    ...   
393          82       1            ford mustang gl               0.030824   
394          82       2                  vw pickup               0.024413   
395          82       1              dodge rampage               0.036601   
396          82       1                ford ranger               0.030095   
397          82       1                 chevy s-10               0.030147   

     performance_score  
0             0.061644  
1             0.046710  
2             0.057625  
3             0.055928  
4             0.051754  
..                 ...  
393           0.150968  
394           0.508169  
395           0.161743  
396           0.198400  
397           0.221103  

[398 rows x 11 columns]

In [73]:
# 8. Visualization Preparation  Generate a summary DataFrame with: Average mpg, weight, and horsepower for each model_year.

In [75]:
summary = data.groupby('model year')[['mpg', 'weight', 'horsepower']].mean().reset_index()
summary

model year        mpg       weight  horsepower
0           70  17.689655  3372.793103  147.827586
1           71  21.250000  2995.428571  106.553571
2           72  18.714286  3237.714286  120.178571
3           73  17.100000  3419.025000  130.475000
4           74  22.703704  2877.925926   94.203704
5           75  20.266667  3176.800000  101.066667
6           76  21.573529  3078.735294  101.117647
7           77  23.375000  2997.357143  105.071429
8           78  24.061111  2861.805556   99.694444
9           79  25.093103  3055.344828  101.206897
10          80  33.696552  2436.655172   78.586207
11          81  30.334483  2522.931034   81.465517
12          82  31.709677  2453.548387   81.854839

In [76]:
# 9. Exporting Data 
# Save a subset of the data containing only mpg, cylinders, horsepower, and weight 
# for cars with mpg > 30 into a CSV file named high_mpg_cars.csv.

In [84]:
high_mpg_cars = data[data['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]
high_mpg_cars


mpg  cylinders  horsepower  weight
53   31.0          4        65.0    1773
54   35.0          4        69.0    1613
129  31.0          4        67.0    1950
131  32.0          4        65.0    1836
144  31.0          4        52.0    1649
..    ...        ...         ...     ...
390  32.0          4        96.0    2665
391  36.0          4        84.0    2370
394  44.0          4        52.0    2130
395  32.0          4        84.0    2295
397  31.0          4        82.0    2720

[85 rows x 4 columns]

In [85]:
high_mpg_cars.to_csv('high_mpg_cars.csv', index=False)
print("The file 'high_mpg_cars.csv' has been successfully created!")

The file 'high_mpg_cars.csv' has been successfully created!


In [ ]:
# 10. Finding Anomalies 
# Identify potential outliers in the mpg column using the Interquartile Range (IQR) 
# method. Specifically: 
# ● Calculate the IQR for mpg. 
# ● Define outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * 
# IQR. 
# ● Create a DataFrame of cars classified as outliers, displaying car_name, mpg, 
# and model_year.

In [90]:

Q1 = data['mpg'].quantile(0.25)  
Q3 = data['mpg'].quantile(0.75)  
IQR = Q3 - Q1     

print("Q1",Q1)
print("Q3",Q3)
print("IQR",IQR)

Q1 17.5
Q3 29.0
IQR 11.5


In [91]:

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print("Lower Bound",lower_bound)
print("Upper Bound",upper_bound)

Lower Bound 0.25
Upper Bound 46.25


In [93]:
outliers = data[(data['mpg'] < lower_bound) | (data['mpg'] > upper_bound)][['car name', 'mpg', 'model year']]
outliers

car name   mpg  model year
322  mazda glc  46.6          80